export const GRAPH_LABEL_MAP = {
  dateFilterLabel: 'טווח תאריכים',
  mailCountFilterLabel: 'סך מיילים בצומת',
  fullscreen: 'מסך מלא',
  minimize: 'מזעור',
  close: 'סגור',
  searchPlaceholder: 'חיפוש צומת',
  mailCount: 'מיילים',
  connections: 'קשרים',
  noSelection: 'לחץ על צומת או קשר לצפייה במיילים',
  sortByMails: 'מיילים',
  sortByDegree: 'דרגה',
  sortByMailsInfo: 'מסונן לפי כמות מיילים בצומת',
  sortByDegreeInfo: 'מסונן לפי כמות קשרים של צומת',
  zoomIn: 'הגדל',
  zoomOut: 'הקטן',
  recenter: 'מרכז',
  loadingGraph: 'טוען גרף...',
};
