export const INBOX_LABEL_MAP = {
  mails: 'מיילים',
  noMails: 'אין מיילים',
  attachments: 'קבצים מצורפים',
  export: 'ייצוא',
  translate: 'תרגום',
  markAsUnread: 'סמן כלא נקרא',
  encoding: 'קידוד',
  download: 'הורדה',
  downloadAll: 'הורד הכל',
  from: 'מאת',
  to: 'אל',
  cc: 'העתק',
  bcc: 'העתק מוסתר',
  noMailSelected: 'לא נבחר מייל',
  exportTooltip: 'סימון מיילים לייצוא',
  cancel: 'ביטול',
  exportWithCount: 'יצוא',
  sortOldToNew: 'מהישן לחדש',
  sortNewToOld: 'מהחדש לישן',
  unreadTooltip: 'לא נקרא',
  readTooltip: 'נקרא',
  translateTooltip: 'תרגם',
};
